# DO NOT REMOVE THIS
theme = "hugo-theme-codex"

# Override these settings with your own
title = "realm"
languageCode = "en-us"
baseURL = "https://smaran-m.github.io/"
copyright = "© 2023"

# Add your Disqus shortname here.
# disqusShortname = ""

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = ""

# Optional params
[params]
  # Follow the Hugo date/time format reference here:
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/smaran_"
  github = "https://github.com/smaran-m"
  email = "mailto:smaran@gatech.edu"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  linkedin = "https://www.linkedin.com/in/smaran-mishra/"
  # youtube = "https://www.youtube.com/channel/<your channel>"

  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported:
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Twitter", "GitHub", "Email", "LinkedIn"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "ㅤhome"
  name = "ㅤhome"
  title = "ㅤHome"
  url = "/"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "about"
  url = "/blog/hello"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = "projects"
  name = "projects"
  title = "Projects"
  url = "/projects"